name: Jest Tests

on: [pull_request]

jobs:
    jest-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.16.0
            - run: npm ci
            - run: npm test
